modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "CC0-1.0"

[[mods]]
modId = "tiny_config"
version = "${version}"
displayName = "Tiny Config"
authors = "Daedelus"
description = '''
A very small config lib
'''
logoFile = "logo.png"

[[dependencies.tiny_config]]
modId = "neoforge"
type = "required"
versionRange = "[26.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.tiny_config]]
modId = "minecraft"
type = "required"
versionRange = "[26.1,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "tiny_config.mixins.json"
